import type { DebugPacket, EvidenceLine, RawDumpResult, Warning } from "./types.js";

export const AI_TRIAGE_INSTRUCTIONS =
  "You are reading a redacted \"debug packet\" generated by Safe Log Explainer, not a raw log. " +
  "Values matching common sensitive-data shapes (emails, IP addresses, tokens, credentials, user IDs, etc.) have already " +
  "been replaced with `[REDACTED:type]` markers — treat any such marker as an unknown value, never " +
  "guess or invent what it might be. Some sensitive data may not have been caught; if a value looks " +
  "unusually specific for a shareable log (an internal hostname, account number, etc.), flag it " +
  "rather than restate it. This packet may be a curated excerpt of a larger log, so the absence of a " +
  "detail here does not mean it is absent from the real log.\n\n" +
  "Using only the information in this packet, write a triage review structured around these five " +
  "questions:\n\n" +
  "1. What is the most sensible investigation path?\n" +
  "2. What are the strongest clues?\n" +
  "3. What are the unknowns?\n" +
  "4. What would you ask or check next?\n" +
  "5. How would you explain this to another developer, to support, or to a client?\n\n" +
  "This is triage guidance only, not a diagnosis. A human must confirm findings against the real " +
  "system (\"Human review required\" below) before acting on them.";

function renderInstructionsSection(): string[] {
  return ["## Instructions for AI assistants", "", AI_TRIAGE_INSTRUCTIONS, ""];
}

function renderWarningsSection(warnings: Warning[]): string[] {
  const lines = ["## Sensitive-data warnings", ""];
  if (warnings.length === 0) {
    lines.push("No sensitive-data patterns detected.", "");
  } else {
    for (const warning of warnings) {
      const suffix = warning.count > 1 ? ` (×${warning.count})` : "";
      lines.push(`- ${warning.type}: \`${warning.value}\`${suffix}`);
    }
    lines.push("");
  }
  return lines;
}

function renderEvidenceLines(entries: EvidenceLine[]): string[] {
  if (entries.length === 0) return ["No relevant lines extracted.", ""];
  const lines: string[] = [];
  let previousLine: number | null = null;
  for (const entry of entries) {
    if (previousLine !== null && entry.line > previousLine + 1) {
      lines.push("- …");
    }
    const tag = entry.isMatch ? "match" : "context";
    lines.push(`- \`L${entry.line}\` [${tag}]: \`${entry.text}\``);
    previousLine = entry.line;
  }
  lines.push("");
  return lines;
}

export function toMarkdown(packet: DebugPacket, warnings: Warning[]): string {
  const lines: string[] = [];

  lines.push("# Debug Packet", "");
  lines.push(...renderInstructionsSection());
  lines.push("## Summary", "");
  lines.push(packet.summary, "");
  lines.push("## Error category", "");
  lines.push(packet.category, "");
  lines.push("## Likely cause", "");
  lines.push(packet.likelyCause, "");
  lines.push("## Context", "");
  lines.push(`- Correlation ID: ${packet.context.correlationId ?? "Not found"}`);
  lines.push(`- Endpoint: ${packet.context.endpoint ?? "Not found"}`);
  lines.push(`- Status: ${packet.context.status ?? "Not found"}`);
  lines.push(`- Duration: ${packet.context.durationMs ? `${packet.context.durationMs}ms` : "Not found"}`, "");
  lines.push("## Relevant lines", "");
  lines.push(...renderEvidenceLines(packet.relevantLines));
  lines.push("## What to check next", "");
  packet.nextChecks.forEach((check, index) => {
    lines.push(`${index + 1}. ${check}`);
  });
  lines.push("");
  lines.push("## Confidence", "");
  lines.push(packet.confidence, "");
  lines.push(...renderWarningsSection(warnings));
  lines.push("## Human review required", "");
  lines.push("Yes. This tool provides triage guidance only.");

  return `${lines.join("\n")}\n`;
}

export function toJson(packet: DebugPacket, warnings: Warning[]): string {
  return JSON.stringify({ instructions: AI_TRIAGE_INSTRUCTIONS, packet, warnings }, null, 2);
}

export function toMarkdownRawDump(result: RawDumpResult, warnings: Warning[]): string {
  const lines: string[] = [];

  lines.push("# Debug Packet: Raw Dump", "");
  lines.push(...renderInstructionsSection());
  lines.push("## Overview", "");
  lines.push(`- Lines analysed: ${result.totalLines - result.truncatedLineCount} of ${result.totalLines}`);

  if (result.truncatedLineCount > 0) {
    lines.push(`- Truncated lines: ${result.truncatedLineCount} (excluded from analysis)`);
  }

  lines.push(`- Matches found: ${result.matches.length}`);
  lines.push(`- Uncategorized relevant lines: ${result.uncategorizedLineCount}`, "");

  if (result.matches.length === 0) {
    lines.push("No known pattern was confidently matched anywhere in this dump.", "");
  } else {
    result.matches.forEach((match, index) => {
      lines.push(`## Match ${index + 1}: ${match.category}`, "");
      lines.push(match.summary, "");
      lines.push("### Likely cause", "");
      lines.push(match.likelyCause, "");
      lines.push("### Confidence", "");
      lines.push(match.confidence, "");
      lines.push("### Evidence", "");
      lines.push(...renderEvidenceLines(match.relevantLines));
      lines.push("### What to check next", "");
      match.nextChecks.forEach((check, checkIndex) => {
        lines.push(`${checkIndex + 1}. ${check}`);
      });
      lines.push("");
    });

    if (result.additionalMatchCount > 0) {
      lines.push(
        `_${result.additionalMatchCount} additional lower-confidence match${result.additionalMatchCount === 1 ? "" : "es"} not shown._`,
        ""
      );
    }
  }

  lines.push("## Context", "");
  lines.push(`- Correlation ID: ${result.context.correlationId ?? "Not found"}`);
  lines.push(`- Endpoint: ${result.context.endpoint ?? "Not found"}`);
  lines.push(`- Status: ${result.context.status ?? "Not found"}`);
  lines.push(`- Duration: ${result.context.durationMs ? `${result.context.durationMs}ms` : "Not found"}`, "");
  lines.push(...renderWarningsSection(warnings));
  lines.push("## Human review required", "");
  lines.push("Yes. This tool provides triage guidance only.");

  return `${lines.join("\n")}\n`;
}

export function toJsonRawDump(result: RawDumpResult, warnings: Warning[]): string {
  return JSON.stringify({ instructions: AI_TRIAGE_INSTRUCTIONS, result, warnings }, null, 2);
}
